### ISSUE TITLE
NaN Timestamps and Text Order Errors with Japanese Audio

### ISSUE THREAD

**Issue by terrymilet** [echogarden-project/echogarden#109]
Hello,
While aligning Japanese audio and text, I encountered an issue where the subtitle timestamps display as NaN:NaN:NaN,NaN, and text that should appear later is incorrectly placed earlier, despite the timestamps (where present) suggesting the correct position.

Here is the command I used:
echogarden align G:\3-水属性的魔法师3\1.mp3 G:\3-水属性的魔法师3\1.txt G:\3-水属性的魔法师3\1.srt G:\3-水属性的魔法师3\1.json --engine=whisper --whisper.model=base

I tested previous versions and found that v2.5.1, v2.5.2, and v2.6.0 work correctly. However, in v2.7.0 and v2.8.0, the alignment process fails and no valid subtitles are generated.

Below is an example of the malformed subtitle output:
11  
00:00:33,093 --> NaN:NaN:NaN,NaN  
品物が上質なお店は、店員さんの接客も上質なのだ。  

12  
NaN:NaN:NaN,NaN --> NaN:NaN:NaN,NaN  
頬をひくひくさせているが、  

13  
00:00:38,476 --> NaN:NaN:NaN,NaN  
涼の後ろでは、アベルが値札を見て、  

14  
00:00:41,376 --> 00:00:43,467  
頬をひくひくさせているが、  

15  
00:00:43,467 --> 00:00:47,874  
そのことには誰も気付かなかった……。  

16  
00:00:47,874 --> 00:00:50,418  
ルンの街の北側。

The correct order of the text should be as follows:
品物が上質なお店は、店員さんの接客も上質なのだ。
涼の後ろでは、アベルが値札を見て、
頬をひくひくさせているが、
そのことには誰も気付かなかった……。
ルンの街の北側。

**Comment by terrymilet** [comment]
[1.zip](https://github.com/user-attachments/files/21968135/1.zip)

**Comment by rotemdan** [comment]
The issue was that during conversion between word timeline to segment/sentence timeline, I applied whitespace processing before the split paragraphs were processed so it broke the offsets, causing many different issues.

The issue wasn't specific to any language, so it was actually very significant, and hasn't been reported for some reason.

I published `v2.9.3` with a fix.

**Comment by terrymilet** [comment]
I tested with the latest version, but some subtitles still show NaN:NaN:NaN,NaN timestamps.
I suspect it might be a segmentation issue. I’ve observed three cases where NaN occurs:

1.When a sentence ends with multiple punctuation marks:
Only the first punctuation mark is kept at the end of the segment; the rest are assigned to the next segment. (e.g. ……〉」, ？」, ！」, ？), ！), etc.)
Example:

text
487
00:25:09,605 --> 00:25:11,684
〈ブレイドラング…

488
00:25:11,684 --> NaN:NaN:NaN,NaN
…〉」

「〈ファイアーボール〉」

489
NaN:NaN:NaN,NaN --> NaN:NaN:NaN,NaN
「〈ファイアーボール〉」


2.When a special symbol appears as a separate segment:
The symbol is incorrectly merged into the next segment.
Example:

text
660
00:34:19,807 --> 00:34:25,441
…さすがに、全く相手にならなかったが……。

661
00:34:25,441 --> NaN:NaN:NaN,NaN
◆

翌朝、勇者パーティー一行は、準備された別館で朝食。

3.When a very short word forms a separate segment:
The short segment is incorrectly merged into the next one.
Example:

text
1562
01:22:20,755 --> NaN:NaN:NaN,NaN
「は？」

調子の外れた声で聞き返したのは、

1563
NaN:NaN:NaN,NaN --> NaN:NaN:NaN,NaN
調子の外れた声で聞き返したのは、
